### ISSUE TITLE
Migrate DS_Stores - without modifying folder dates?

### ISSUE THREAD

**Issue by mralexgray** [binaryage/asepsis#12]
Is there any easy solution to be able to `migrate` all the `DS_Store` files out of a directory _without modifying_ the date of every single folder?

I'd love to be able to purge the suckers from a directory I work a lot with - but cannot afford to lose all the modification dates, as that is how I track a lot of the stuff.

**Comment by mralexgray** [comment]
Never got a chance to thank you for this... so, thanks!

**Comment by darwin** [comment]
:+1:
