### ISSUE TITLE
Asepsis updater: Disable failed update notification

### ISSUE THREAD

**Issue by fhemberger** [binaryage/asepsis#14]
I use Little Snitch to maintain several network configurations. One of the firewall rules is to block software updates via http on untrusted networks.

Other Mac applications fail silently when no network connection for updating could be established, but the Asepsis updater always shows an error message instead. It would be great if the behavior could be altered to match the general behavior of Mac applications and suppress the error (or make it at least configurable).

**Comment by dustindowell22** [comment]
Is there anyway to remove the notification as well? It pops up like every hour. Or at least an option to disable automatic update checking would be nice.

**Comment by fhemberger** [comment]
@dustindowell22 Create an empty file `~/.asepsis-suppress-update-errors`, that should do the trick.

**Comment by dustindowell22** [comment]
@fhemberger Nice. Thanks.
