### ISSUE TITLE
Support for Mac OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by ludekdolejsky** [binaryage/asepsis#16]
Is there a plan to support the new Mac OS X?

**Comment by dgellow** [comment]
any news ?

**Comment by darwin** [comment]
http://asepsis.binaryage.com/#v1.5
v1.5 should work under Yosemite, some people reported issues with 10.10.3 update

**Comment by dgellow** [comment]
@darwin That's justly my situation. I updated my system from 10.9.x to 10.10.3. 
Every 3-4 hours a popup popped up and told me that asepsis is not supported by the current version.
Today I have reinstall asepsis and everything seems okay now (I haven't see the popup yet).

Thank you for your response.
