### ISSUE TITLE
library naming issue, causing lots logs in console, and causing errors

### ISSUE THREAD

**Issue by revintec** [binaryage/asepsis#29]
something like this prints a lot(totally flooded the console), and followed by error messages:
com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.Finder.248) Conflicts exist in System services. Randomly deciding: path1 = /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/XPCServices/com.apple.desktopservices.NumbersConverterXPCService64.xpc, path2 = /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A_/XPCServices/com.apple.desktopservices.NumbersConverterXPCService64.xpc

com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.Finder.248) Failed to bootstrap path: path = /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/XPCServices/com.apple.desktopservices.NumbersConverterXPCService64.xpc, error = 130: The system encountered a condition where behavior was undefined

// =========================================================
so I believe you should rename A_ to something like A_original to avoid this mess?
(I've noticed A_Backup is not showing here, because it have a longer name?)
I've reported earlier, that asepsis sometimes not working correctly, maybe this is the issue?
judging from the log, the system may load A_ which bypass asepsis?

**Comment by lowell** [comment]
Appears to be related to #28. Discussion currently [here](http://discuss.binaryage.com/t/1-5-system-log-chattiness-in-yosemite/2351).

**Comment by revintec** [comment]
Yes it's a dup, sorry for that...
