### ISSUE TITLE
Document uninstallation under El Capitan

### ISSUE THREAD

**Issue by genevera** [binaryage/asepsis#37]
It seems like uninstalling this could potentially brick one's system if done incorrectly.  Is there a guide to / script for doing this the correct way?

**Comment by darwin** [comment]
Did you see https://asepsis.binaryage.com/#panic-mode?

You should run `sudo asepsisctl uninstall_wrapper`

The script tries not to screw this up:
https://github.com/binaryage/asepsis/blob/master/ctl/cmd/uninstall_wrapper.rb

You could read it and uninstall it by hand, but it is not easy. Definitely have a backup of your system on a Time Machine or somewhere.
